table _Measures
	lineageTag: 3fa62e18-cd29-4597-a391-fb2a1bbd7baf

	measure 'Open Amount Function' = ```
			
			
			ChrisBarber.Finance.AccountRecievable('Date','Date'[Date],'AR Detail','AR Detail'[Due Date],'AR Detail'[Due Amount],'AR Detail'[Payment Date],'Aging Range','Aging Range'[Min],'Aging Range'[Max])
			
			
			
			
			```
		formatString: #,0
		lineageTag: 072058b1-fdd7-4406-aa56-3c6e5aca9086

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

