DEFINE
    /// Creates the P&L Lines
    FUNCTION __Fn_PnL_Indicators = (
    amount: EXPR
) =>

VAR NCLD_filter_context_calculated_table =
    CALCULATETABLE(
        Layout,
        REMOVEFILTERS( Layout ),
        Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
        Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
    )
VAR step1_lineitem = MAX( Account[Account Type Indicator] )
VAR step2_subtotal =
    CALCULATE( MAX( Account[Account Type Indicator] ), NCLD_filter_context_calculated_table )

VAR result = COALESCE( step1_lineitem, step2_subtotal )
RETURN
    result

