table 'Effective Date'
	lineageTag: 1154eef3-e3a7-4fae-92b3-37cd4dde9158
	dataCategory: Time

	column 'Fiscal Date'
		dataType: dateTime
		isKey
		formatString: mm/dd/yyyy
		lineageTag: 56ecf748-5855-4ab2-9210-a56e00ad40b5
		summarizeBy: none
		sourceColumn: Fiscal Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE"]}

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: d50fdd4b-085d-4231-96df-18d541ee3654
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: string
		lineageTag: aa0e2677-d8ba-4543-ba78-8d0d81607064
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Period'
		dataType: string
		lineageTag: 39601040-00bc-46f7-9ce2-7fbc0da22ac2
		summarizeBy: none
		sourceColumn: Fiscal Period

		annotation SummarizationSetBy = Automatic

	partition 'Effective Date' = m
		mode: import
		source =
				let
				    Source = Binary.FromText(
				"RmlzY2FsIERhdGUJRmlzY2FsIFllYXIJRmlzY2FsIFF1YXJ0ZXIJRmlzY2FsIFBlcmlvZAozMCBTZXB0ZW1iZXIgMjAyMwkyMDIzCVEzCVA5CjI5IFNlcHRlbWJlciAyMDIzCTIwMjMJUTMJUDkKMjggU2VwdGVtYmVyIDIwMjMJMjAyMwlRMwlQOQoyNyBTZXB0ZW1iZXIgMjAyMwkyMDIzCVEzCVA5CjI2IFNlcHRlbWJlciAyMDIzCTIwMjMJUTMJUDkKMjUgU2VwdGVtYmVyIDIwMjMJMjAyMwlRMwlQOQoyNCBTZXB0ZW1iZXIgMjAyMwkyMDIzCVEzCVA5CjIzIFNlcHRlbWJlciAyMDIzCTIwMjMJUTMJUDkKMjIgU2VwdGVtYmVyIDIwMjMJMjAyMwlRMwlQOQoyMSBTZXB0ZW1iZXIgMjAyMwkyMDIzCVEzCVA5CjIwIFNlcHRlbWJlciAyMDIzCTIwMjMJUTMJUDkKMTkgU2VwdGVtYmVyIDIwMjMJMjAyMwlRMwlQOQoxOCBTZXB0ZW1iZXIgMjAyMwkyMDIzCVEzCVA5CjE3IFNlcHRlbWJlciAyMDIzCTIwMjMJUTMJUDkKMTYgU2VwdGVtYmVyIDIwMjMJMjAyMwlRMwlQOQoxNSBTZXB0ZW1iZXIgMjAyMwkyMDIzCVEzCVA5CjE0IFNlcHRlbWJlciAyMDIzCTIwMjMJUTMJUDkKMTMgU2VwdGVtYmVyIDIwMjMJMjAyMwlRMwlQOQoxMiBTZXB0ZW1iZXIgMjAyMwkyMDIzCVEzCVA5CjExIFNlcHRlbWJlciAyMDIzCTIwMjMJUTMJUDkKMTAgU2VwdGVtYmVyIDIwMjMJMjAyMwlRMwlQOQowOSBTZXB0ZW1iZXIgMjAyMwkyMDIzCVEzCVA5CjA4IFNlcHRlbWJlciAyMDIzCTIwMjMJUTMJUDkKMDcgU2VwdGVtYmVyIDIwMjMJMjAyMwlRMwlQOQowNiBTZXB0ZW1iZXIgMjAyMwkyMDIzCVEzCVA5CjA1IFNlcHRlbWJlciAyMDIzCTIwMjMJUTMJUDkKMDQgU2VwdGVtYmVyIDIwMjMJMjAyMwlRMwlQOQowMyBTZXB0ZW1iZXIgMjAyMwkyMDIzCVEzCVA5CjAyIFNlcHRlbWJlciAyMDIzCTIwMjMJUTMJUDkKMDEgU2VwdGVtYmVyIDIwMjMJMjAyMwlRMwlQOQozMSBBdWd1c3QgMjAyMwkyMDIzCVEzCVA4CjMwIEF1Z3VzdCAyMDIzCTIwMjMJUTMJUDgKMjkgQXVndXN0IDIwMjMJMjAyMwlRMwlQOAoyOCBBdWd1c3QgMjAyMwkyMDIzCVEzCVA4CjI3IEF1Z3VzdCAyMDIzCTIwMjMJUTMJUDgKMjYgQXVndXN0IDIwMjMJMjAyMwlRMwlQOAoyNSBBdWd1c3QgMjAyMwkyMDIzCVEzCVA4CjI0IEF1Z3VzdCAyMDIzCTIwMjMJUTMJUDgKMjMgQXVndXN0IDIwMjMJMjAyMwlRMwlQOAoyMiBBdWd1c3QgMjAyMwkyMDIzCVEzCVA4CjIxIEF1Z3VzdCAyMDIzCTIwMjMJUTMJUDgKMjAgQXVndXN0IDIwMjMJMjAyMwlRMwlQOAoxOSBBdWd1c3QgMjAyMwkyMDIzCVEzCVA4CjE4IEF1Z3VzdCAyMDIzCTIwMjMJUTMJUDgKMTcgQXVndXN0IDIwMjMJMjAyMwlRMwlQOAoxNiBBdWd1c3QgMjAyMwkyMDIzCVEzCVA4CjE1IEF1Z3VzdCAyMDIzCTIwMjMJUTMJUDgKMTQgQXVndXN0IDIwMjMJMjAyMwlRMwlQOAoxMyBBdWd1c3QgMjAyMwkyMDIzCVEzCVA4CjEyIEF1Z3VzdCAyMDIzCTIwMjMJUTMJUDgKMTEgQXVndXN0IDIwMjMJMjAyMwlRMwlQOAoxMCBBdWd1c3QgMjAyMwkyMDIzCVEzCVA4CjA5IEF1Z3VzdCAyMDIzCTIwMjMJUTMJUDgKMDggQXVndXN0IDIwMjMJMjAyMwlRMwlQOAowNyBBdWd1c3QgMjAyMwkyMDIzCVEzCVA4CjA2IEF1Z3VzdCAyMDIzCTIwMjMJUTMJUDgKMDUgQXVndXN0IDIwMjMJMjAyMwlRMwlQOAowNCBBdWd1c3QgMjAyMwkyMDIzCVEzCVA4CjAzIEF1Z3VzdCAyMDIzCTIwMjMJUTMJUDgKMDIgQXVndXN0IDIwMjMJMjAyMwlRMwlQOAowMSBBdWd1c3QgMjAyMwkyMDIzCVEzCVA4CjMxIEp1bHkgMjAyMwkyMDIzCVEzCVA3CjMwIEp1bHkgMjAyMwkyMDIzCVEzCVA3CjI5IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjI4IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjI3IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjI2IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjI1IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjI0IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjIzIEp1bHkgMjAyMwkyMDIzCVEzCVA3CjIyIEp1bHkgMjAyMwkyMDIzCVEzCVA3CjIxIEp1bHkgMjAyMwkyMDIzCVEzCVA3CjIwIEp1bHkgMjAyMwkyMDIzCVEzCVA3CjE5IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjE4IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjE3IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjE2IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjE1IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjE0IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjEzIEp1bHkgMjAyMwkyMDIzCVEzCVA3CjEyIEp1bHkgMjAyMwkyMDIzCVEzCVA3CjExIEp1bHkgMjAyMwkyMDIzCVEzCVA3CjEwIEp1bHkgMjAyMwkyMDIzCVEzCVA3CjA5IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjA4IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjA3IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjA2IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjA1IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjA0IEp1bHkgMjAyMwkyMDIzCVEzCVA3CjAzIEp1bHkgMjAyMwkyMDIzCVEzCVA3CjAyIEp1bHkgMjAyMwkyMDIzCVEzCVA3CjAxIEp1bHkgMjAyMwkyMDIzCVEzCVA3CjMwIFNlcHRlbWJlciAyMDI0CTIwMjQJUTMJUDkKMjkgU2VwdGVtYmVyIDIwMjQJMjAyNAlRMwlQOQoyOCBTZXB0ZW1iZXIgMjAyNAkyMDI0CVEzCVA5CjI3IFNlcHRlbWJlciAyMDI0CTIwMjQJUTMJUDkKMjYgU2VwdGVtYmVyIDIwMjQJMjAyNAlRMwlQOQoyNSBTZXB0ZW1iZXIgMjAyNAkyMDI0CVEzCVA5CjI0IFNlcHRlbWJlciAyMDI0CTIwMjQJUTMJUDkKMjMgU2VwdGVtYmVyIDIwMjQJMjAyNAlRMwlQOQoyMiBTZXB0ZW1iZXIgMjAyNAkyMDI0CVEzCVA5CjIxIFNlcHRlbWJlciAyMDI0CTIwMjQJUTMJUDkKMjAgU2VwdGVtYmVyIDIwMjQJMjAyNAlRMwlQOQoxOSBTZXB0ZW1iZXIgMjAyNAkyMDI0CVEzCVA5CjE4IFNlcHRlbWJlciAyMDI0CTIwMjQJUTMJUDkKMTcgU2VwdGVtYmVyIDIwMjQJMjAyNAlRMwlQOQoxNiBTZXB0ZW1iZXIgMjAyNAkyMDI0CVEzCVA5CjE1IFNlcHRlbWJlciAyMDI0CTIwMjQJUTMJUDkKMTQgU2VwdGVtYmVyIDIwMjQJMjAyNAlRMwlQOQoxMyBTZXB0ZW1iZXIgMjAyNAkyMDI0CVEzCVA5CjEyIFNlcHRlbWJlciAyMDI0CTIwMjQJUTMJUDkKMTEgU2VwdGVtYmVyIDIwMjQJMjAyNAlRMwlQOQoxMCBTZXB0ZW1iZXIgMjAyNAkyMDI0CVEzCVA5CjA5IFNlcHRlbWJlciAyMDI0CTIwMjQJUTMJUDkKMDggU2VwdGVtYmVyIDIwMjQJMjAyNAlRMwlQOQowNyBTZXB0ZW1iZXIgMjAyNAkyMDI0CVEzCVA5CjA2IFNlcHRlbWJlciAyMDI0CTIwMjQJUTMJUDkKMDUgU2VwdGVtYmVyIDIwMjQJMjAyNAlRMwlQOQowNCBTZXB0ZW1iZXIgMjAyNAkyMDI0CVEzCVA5CjAzIFNlcHRlbWJlciAyMDI0CTIwMjQJUTMJUDkKMDIgU2VwdGVtYmVyIDIwMjQJMjAyNAlRMwlQOQowMSBTZXB0ZW1iZXIgMjAyNAkyMDI0CVEzCVA5CjMxIEF1Z3VzdCAyMDI0CTIwMjQJUTMJUDgKMzAgQXVndXN0IDIwMjQJMjAyNAlRMwlQOAoyOSBBdWd1c3QgMjAyNAkyMDI0CVEzCVA4CjI4IEF1Z3VzdCAyMDI0CTIwMjQJUTMJUDgKMjcgQXVndXN0IDIwMjQJMjAyNAlRMwlQOAoyNiBBdWd1c3QgMjAyNAkyMDI0CVEzCVA4CjI1IEF1Z3VzdCAyMDI0CTIwMjQJUTMJUDgKMjQgQXVndXN0IDIwMjQJMjAyNAlRMwlQOAoyMyBBdWd1c3QgMjAyNAkyMDI0CVEzCVA4CjIyIEF1Z3VzdCAyMDI0CTIwMjQJUTMJUDgKMjEgQXVndXN0IDIwMjQJMjAyNAlRMwlQOAoyMCBBdWd1c3QgMjAyNAkyMDI0CVEzCVA4CjE5IEF1Z3VzdCAyMDI0CTIwMjQJUTMJUDgKMTggQXVndXN0IDIwMjQJMjAyNAlRMwlQOAoxNyBBdWd1c3QgMjAyNAkyMDI0CVEzCVA4CjE2IEF1Z3VzdCAyMDI0CTIwMjQJUTMJUDgKMTUgQXVndXN0IDIwMjQJMjAyNAlRMwlQOAoxNCBBdWd1c3QgMjAyNAkyMDI0CVEzCVA4CjEzIEF1Z3VzdCAyMDI0CTIwMjQJUTMJUDgKMTIgQXVndXN0IDIwMjQJMjAyNAlRMwlQOAoxMSBBdWd1c3QgMjAyNAkyMDI0CVEzCVA4CjEwIEF1Z3VzdCAyMDI0CTIwMjQJUTMJUDgKMDkgQXVndXN0IDIwMjQJMjAyNAlRMwlQOAowOCBBdWd1c3QgMjAyNAkyMDI0CVEzCVA4CjA3IEF1Z3VzdCAyMDI0CTIwMjQJUTMJUDgKMDYgQXVndXN0IDIwMjQJMjAyNAlRMwlQOAowNSBBdWd1c3QgMjAyNAkyMDI0CVEzCVA4CjA0IEF1Z3VzdCAyMDI0CTIwMjQJUTMJUDgKMDMgQXVndXN0IDIwMjQJMjAyNAlRMwlQOAowMiBBdWd1c3QgMjAyNAkyMDI0CVEzCVA4CjAxIEF1Z3VzdCAyMDI0CTIwMjQJUTMJUDgKMzEgSnVseSAyMDI0CTIwMjQJUTMJUDcKMzAgSnVseSAyMDI0CTIwMjQJUTMJUDcKMjkgSnVseSAyMDI0CTIwMjQJUTMJUDcKMjggSnVseSAyMDI0CTIwMjQJUTMJUDcKMjcgSnVseSAyMDI0CTIwMjQJUTMJUDcKMjYgSnVseSAyMDI0CTIwMjQJUTMJUDcKMjUgSnVseSAyMDI0CTIwMjQJUTMJUDcKMjQgSnVseSAyMDI0CTIwMjQJUTMJUDcKMjMgSnVseSAyMDI0CTIwMjQJUTMJUDcKMjIgSnVseSAyMDI0CTIwMjQJUTMJUDcKMjEgSnVseSAyMDI0CTIwMjQJUTMJUDcKMjAgSnVseSAyMDI0CTIwMjQJUTMJUDcKMTkgSnVseSAyMDI0CTIwMjQJUTMJUDcKMTggSnVseSAyMDI0CTIwMjQJUTMJUDcKMTcgSnVseSAyMDI0CTIwMjQJUTMJUDcKMTYgSnVseSAyMDI0CTIwMjQJUTMJUDcKMTUgSnVseSAyMDI0CTIwMjQJUTMJUDcKMTQgSnVseSAyMDI0CTIwMjQJUTMJUDcKMTMgSnVseSAyMDI0CTIwMjQJUTMJUDcKMTIgSnVseSAyMDI0CTIwMjQJUTMJUDcKMTEgSnVseSAyMDI0CTIwMjQJUTMJUDcKMTAgSnVseSAyMDI0CTIwMjQJUTMJUDcKMDkgSnVseSAyMDI0CTIwMjQJUTMJUDcKMDggSnVseSAyMDI0CTIwMjQJUTMJUDcKMDcgSnVseSAyMDI0CTIwMjQJUTMJUDcKMDYgSnVseSAyMDI0CTIwMjQJUTMJUDcKMDUgSnVseSAyMDI0CTIwMjQJUTMJUDcKMDQgSnVseSAyMDI0CTIwMjQJUTMJUDcKMDMgSnVseSAyMDI0CTIwMjQJUTMJUDcKMDIgSnVseSAyMDI0CTIwMjQJUTMJUDcKMDEgSnVseSAyMDI0CTIwMjQJUTMJUDcKMzEgRGVjZW1iZXIgMjAyMwkyMDIzCVE0CVAxMgozMCBEZWNlbWJlciAyMDIzCTIwMjMJUTQJUDEyCjI5IERlY2VtYmVyIDIwMjMJMjAyMwlRNAlQMTIKMjggRGVjZW1iZXIgMjAyMwkyMDIzCVE0CVAxMgoyNyBEZWNlbWJlciAyMDIzCTIwMjMJUTQJUDEyCjI2IERlY2VtYmVyIDIwMjMJMjAyMwlRNAlQMTIKMjUgRGVjZW1iZXIgMjAyMwkyMDIzCVE0CVAxMgoyNCBEZWNlbWJlciAyMDIzCTIwMjMJUTQJUDEyCjIzIERlY2VtYmVyIDIwMjMJMjAyMwlRNAlQMTIKMjIgRGVjZW1iZXIgMjAyMwkyMDIzCVE0CVAxMgoyMSBEZWNlbWJlciAyMDIzCTIwMjMJUTQJUDEyCjIwIERlY2VtYmVyIDIwMjMJMjAyMwlRNAlQMTIKMTkgRGVjZW1iZXIgMjAyMwkyMDIzCVE0CVAxMgoxOCBEZWNlbWJlciAyMDIzCTIwMjMJUTQJUDEyCjE3IERlY2VtYmVyIDIwMjMJMjAyMwlRNAlQMTIKMTYgRGVjZW1iZXIgMjAyMwkyMDIzCVE0CVAxMgoxNSBEZWNlbWJlciAyMDIzCTIwMjMJUTQJUDEyCjE0IERlY2VtYmVyIDIwMjMJMjAyMwlRNAlQMTIKMTMgRGVjZW1iZXIgMjAyMwkyMDIzCVE0CVAxMgoxMiBEZWNlbWJlciAyMDIzCTIwMjMJUTQJUDEyCjExIERlY2VtYmVyIDIwMjMJMjAyMwlRNAlQMTIKMTAgRGVjZW1iZXIgMjAyMwkyMDIzCVE0CVAxMgowOSBEZWNlbWJlciAyMDIzCTIwMjMJUTQJUDEyCjA4IERlY2VtYmVyIDIwMjMJMjAyMwlRNAlQMTIKMDcgRGVjZW1iZXIgMjAyMwkyMDIzCVE0CVAxMgowNiBEZWNlbWJlciAyMDIzCTIwMjMJUTQJUDEyCjA1IERlY2VtYmVyIDIwMjMJMjAyMwlRNAlQMTIKMDQgRGVjZW1iZXIgMjAyMwkyMDIzCVE0CVAxMgowMyBEZWNlbWJlciAyMDIzCTIwMjMJUTQJUDEyCjAyIERlY2VtYmVyIDIwMjMJMjAyMwlRNAlQMTIKMDEgRGVjZW1iZXIgMjAyMwkyMDIzCVE0CVAxMgozMCBOb3ZlbWJlciAyMDIzCTIwMjMJUTQJUDExCjI5IE5vdmVtYmVyIDIwMjMJMjAyMwlRNAlQMTEKMjggTm92ZW1iZXIgMjAyMwkyMDIzCVE0CVAxMQoyNyBOb3ZlbWJlciAyMDIzCTIwMjMJUTQJUDExCjI2IE5vdmVtYmVyIDIwMjMJMjAyMwlRNAlQMTEKMjUgTm92ZW1iZXIgMjAyMwkyMDIzCVE0CVAxMQoyNCBOb3ZlbWJlciAyMDIzCTIwMjMJUTQJUDExCjIzIE5vdmVtYmVyIDIwMjMJMjAyMwlRNAlQMTEKMjIgTm92ZW1iZXIgMjAyMwkyMDIzCVE0CVAxMQoyMSBOb3ZlbWJlciAyMDIzCTIwMjMJUTQJUDExCjIwIE5vdmVtYmVyIDIwMjMJMjAyMwlRNAlQMTEKMTkgTm92ZW1iZXIgMjAyMwkyMDIzCVE0CVAxMQoxOCBOb3ZlbWJlciAyMDIzCTIwMjMJUTQJUDExCjE3IE5vdmVtYmVyIDIwMjMJMjAyMwlRNAlQMTEKMTYgTm92ZW1iZXIgMjAyMwkyMDIzCVE0CVAxMQoxNSBOb3ZlbWJlciAyMDIzCTIwMjMJUTQJUDExCjE0IE5vdmVtYmVyIDIwMjMJMjAyMwlRNAlQMTEKMTMgTm92ZW1iZXIgMjAyMwkyMDIzCVE0CVAxMQoxMiBOb3ZlbWJlciAyMDIzCTIwMjMJUTQJUDExCjExIE5vdmVtYmVyIDIwMjMJMjAyMwlRNAlQMTEKMTAgTm92ZW1iZXIgMjAyMwkyMDIzCVE0CVAxMQowOSBOb3ZlbWJlciAyMDIzCTIwMjMJUTQJUDExCjA4IE5vdmVtYmVyIDIwMjMJMjAyMwlRNAlQMTEKMDcgTm92ZW1iZXIgMjAyMwkyMDIzCVE0CVAxMQowNiBOb3ZlbWJlciAyMDIzCTIwMjMJUTQJUDExCjA1IE5vdmVtYmVyIDIwMjMJMjAyMwlRNAlQMTEKMDQgTm92ZW1iZXIgMjAyMwkyMDIzCVE0CVAxMQowMyBOb3ZlbWJlciAyMDIzCTIwMjMJUTQJUDExCjAyIE5vdmVtYmVyIDIwMjMJMjAyMwlRNAlQMTEKMDEgTm92ZW1iZXIgMjAyMwkyMDIzCVE0CVAxMQozMSBPY3RvYmVyIDIwMjMJMjAyMwlRNAlQMTAKMzAgT2N0b2JlciAyMDIzCTIwMjMJUTQJUDEwCjI5IE9jdG9iZXIgMjAyMwkyMDIzCVE0CVAxMAoyOCBPY3RvYmVyIDIwMjMJMjAyMwlRNAlQMTAKMjcgT2N0b2JlciAyMDIzCTIwMjMJUTQJUDEwCjI2IE9jdG9iZXIgMjAyMwkyMDIzCVE0CVAxMAoyNSBPY3RvYmVyIDIwMjMJMjAyMwlRNAlQMTAKMjQgT2N0b2JlciAyMDIzCTIwMjMJUTQJUDEwCjIzIE9jdG9iZXIgMjAyMwkyMDIzCVE0CVAxMAoyMiBPY3RvYmVyIDIwMjMJMjAyMwlRNAlQMTAKMjEgT2N0b2JlciAyMDIzCTIwMjMJUTQJUDEwCjIwIE9jdG9iZXIgMjAyMwkyMDIzCVE0CVAxMAoxOSBPY3RvYmVyIDIwMjMJMjAyMwlRNAlQMTAKMTggT2N0b2JlciAyMDIzCTIwMjMJUTQJUDEwCjE3IE9jdG9iZXIgMjAyMwkyMDIzCVE0CVAxMAoxNiBPY3RvYmVyIDIwMjMJMjAyMwlRNAlQMTAKMTUgT2N0b2JlciAyMDIzCTIwMjMJUTQJUDEwCjE0IE9jdG9iZXIgMjAyMwkyMDIzCVE0CVAxMAoxMyBPY3RvYmVyIDIwMjMJMjAyMwlRNAlQMTAKMTIgT2N0b2JlciAyMDIzCTIwMjMJUTQJUDEwCjExIE9jdG9iZXIgMjAyMwkyMDIzCVE0CVAxMAoxMCBPY3RvYmVyIDIwMjMJMjAyMwlRNAlQMTAKMDkgT2N0b2JlciAyMDIzCTIwMjMJUTQJUDEwCjA4IE9jdG9iZXIgMjAyMwkyMDIzCVE0CVAxMAowNyBPY3RvYmVyIDIwMjMJMjAyMwlRNAlQMTAKMDYgT2N0b2JlciAyMDIzCTIwMjMJUTQJUDEwCjA1IE9jdG9iZXIgMjAyMwkyMDIzCVE0CVAxMAowNCBPY3RvYmVyIDIwMjMJMjAyMwlRNAlQMTAKMDMgT2N0b2JlciAyMDIzCTIwMjMJUTQJUDEwCjAyIE9jdG9iZXIgMjAyMwkyMDIzCVE0CVAxMAowMSBPY3RvYmVyIDIwMjMJMjAyMwlRNAlQMTAKMzEgRGVjZW1iZXIgMjAyNAkyMDI0CVE0CVAxMgozMCBEZWNlbWJlciAyMDI0CTIwMjQJUTQJUDEyCjI5IERlY2VtYmVyIDIwMjQJMjAyNAlRNAlQMTIKMjggRGVjZW1iZXIgMjAyNAkyMDI0CVE0CVAxMgoyNyBEZWNlbWJlciAyMDI0CTIwMjQJUTQJUDEyCjI2IERlY2VtYmVyIDIwMjQJMjAyNAlRNAlQMTIKMjUgRGVjZW1iZXIgMjAyNAkyMDI0CVE0CVAxMgoyNCBEZWNlbWJlciAyMDI0CTIwMjQJUTQJUDEyCjIzIERlY2VtYmVyIDIwMjQJMjAyNAlRNAlQMTIKMjIgRGVjZW1iZXIgMjAyNAkyMDI0CVE0CVAxMgoyMSBEZWNlbWJlciAyMDI0CTIwMjQJUTQJUDEyCjIwIERlY2VtYmVyIDIwMjQJMjAyNAlRNAlQMTIKMTkgRGVjZW1iZXIgMjAyNAkyMDI0CVE0CVAxMgoxOCBEZWNlbWJlciAyMDI0CTIwMjQJUTQJUDEyCjE3IERlY2VtYmVyIDIwMjQJMjAyNAlRNAlQMTIKMTYgRGVjZW1iZXIgMjAyNAkyMDI0CVE0CVAxMgoxNSBEZWNlbWJlciAyMDI0CTIwMjQJUTQJUDEyCjE0IERlY2VtYmVyIDIwMjQJMjAyNAlRNAlQMTIKMTMgRGVjZW1iZXIgMjAyNAkyMDI0CVE0CVAxMgoxMiBEZWNlbWJlciAyMDI0CTIwMjQJUTQJUDEyCjExIERlY2VtYmVyIDIwMjQJMjAyNAlRNAlQMTIKMTAgRGVjZW1iZXIgMjAyNAkyMDI0CVE0CVAxMgowOSBEZWNlbWJlciAyMDI0CTIwMjQJUTQJUDEyCjA4IERlY2VtYmVyIDIwMjQJMjAyNAlRNAlQMTIKMDcgRGVjZW1iZXIgMjAyNAkyMDI0CVE0CVAxMgowNiBEZWNlbWJlciAyMDI0CTIwMjQJUTQJUDEyCjA1IERlY2VtYmVyIDIwMjQJMjAyNAlRNAlQMTIKMDQgRGVjZW1iZXIgMjAyNAkyMDI0CVE0CVAxMgowMyBEZWNlbWJlciAyMDI0CTIwMjQJUTQJUDEyCjAyIERlY2VtYmVyIDIwMjQJMjAyNAlRNAlQMTIKMDEgRGVjZW1iZXIgMjAyNAkyMDI0CVE0CVAxMgozMCBOb3ZlbWJlciAyMDI0CTIwMjQJUTQJUDExCjI5IE5vdmVtYmVyIDIwMjQJMjAyNAlRNAlQMTEKMjggTm92ZW1iZXIgMjAyNAkyMDI0CVE0CVAxMQoyNyBOb3ZlbWJlciAyMDI0CTIwMjQJUTQJUDExCjI2IE5vdmVtYmVyIDIwMjQJMjAyNAlRNAlQMTEKMjUgTm92ZW1iZXIgMjAyNAkyMDI0CVE0CVAxMQoyNCBOb3ZlbWJlciAyMDI0CTIwMjQJUTQJUDExCjIzIE5vdmVtYmVyIDIwMjQJMjAyNAlRNAlQMTEKMjIgTm92ZW1iZXIgMjAyNAkyMDI0CVE0CVAxMQoyMSBOb3ZlbWJlciAyMDI0CTIwMjQJUTQJUDExCjIwIE5vdmVtYmVyIDIwMjQJMjAyNAlRNAlQMTEKMTkgTm92ZW1iZXIgMjAyNAkyMDI0CVE0CVAxMQoxOCBOb3ZlbWJlciAyMDI0CTIwMjQJUTQJUDExCjE3IE5vdmVtYmVyIDIwMjQJMjAyNAlRNAlQMTEKMTYgTm92ZW1iZXIgMjAyNAkyMDI0CVE0CVAxMQoxNSBOb3ZlbWJlciAyMDI0CTIwMjQJUTQJUDExCjE0IE5vdmVtYmVyIDIwMjQJMjAyNAlRNAlQMTEKMTMgTm92ZW1iZXIgMjAyNAkyMDI0CVE0CVAxMQoxMiBOb3ZlbWJlciAyMDI0CTIwMjQJUTQJUDExCjExIE5vdmVtYmVyIDIwMjQJMjAyNAlRNAlQMTEKMTAgTm92ZW1iZXIgMjAyNAkyMDI0CVE0CVAxMQowOSBOb3ZlbWJlciAyMDI0CTIwMjQJUTQJUDExCjA4IE5vdmVtYmVyIDIwMjQJMjAyNAlRNAlQMTEKMDcgTm92ZW1iZXIgMjAyNAkyMDI0CVE0CVAxMQowNiBOb3ZlbWJlciAyMDI0CTIwMjQJUTQJUDExCjA1IE5vdmVtYmVyIDIwMjQJMjAyNAlRNAlQMTEKMDQgTm92ZW1iZXIgMjAyNAkyMDI0CVE0CVAxMQowMyBOb3ZlbWJlciAyMDI0CTIwMjQJUTQJUDExCjAyIE5vdmVtYmVyIDIwMjQJMjAyNAlRNAlQMTEKMDEgTm92ZW1iZXIgMjAyNAkyMDI0CVE0CVAxMQozMSBPY3RvYmVyIDIwMjQJMjAyNAlRNAlQMTAKMzAgT2N0b2JlciAyMDI0CTIwMjQJUTQJUDEwCjI5IE9jdG9iZXIgMjAyNAkyMDI0CVE0CVAxMAoyOCBPY3RvYmVyIDIwMjQJMjAyNAlRNAlQMTAKMjcgT2N0b2JlciAyMDI0CTIwMjQJUTQJUDEwCjI2IE9jdG9iZXIgMjAyNAkyMDI0CVE0CVAxMAoyNSBPY3RvYmVyIDIwMjQJMjAyNAlRNAlQMTAKMjQgT2N0b2JlciAyMDI0CTIwMjQJUTQJUDEwCjIzIE9jdG9iZXIgMjAyNAkyMDI0CVE0CVAxMAoyMiBPY3RvYmVyIDIwMjQJMjAyNAlRNAlQMTAKMjEgT2N0b2JlciAyMDI0CTIwMjQJUTQJUDEwCjIwIE9jdG9iZXIgMjAyNAkyMDI0CVE0CVAxMAoxOSBPY3RvYmVyIDIwMjQJMjAyNAlRNAlQMTAKMTggT2N0b2JlciAyMDI0CTIwMjQJUTQJUDEwCjE3IE9jdG9iZXIgMjAyNAkyMDI0CVE0CVAxMAoxNiBPY3RvYmVyIDIwMjQJMjAyNAlRNAlQMTAKMTUgT2N0b2JlciAyMDI0CTIwMjQJUTQJUDEwCjE0IE9jdG9iZXIgMjAyNAkyMDI0CVE0CVAxMAoxMyBPY3RvYmVyIDIwMjQJMjAyNAlRNAlQMTAKMTIgT2N0b2JlciAyMDI0CTIwMjQJUTQJUDEwCjExIE9jdG9iZXIgMjAyNAkyMDI0CVE0CVAxMAoxMCBPY3RvYmVyIDIwMjQJMjAyNAlRNAlQMTAKMDkgT2N0b2JlciAyMDI0CTIwMjQJUTQJUDEwCjA4IE9jdG9iZXIgMjAyNAkyMDI0CVE0CVAxMAowNyBPY3RvYmVyIDIwMjQJMjAyNAlRNAlQMTAKMDYgT2N0b2JlciAyMDI0CTIwMjQJUTQJUDEwCjA1IE9jdG9iZXIgMjAyNAkyMDI0CVE0CVAxMAowNCBPY3RvYmVyIDIwMjQJMjAyNAlRNAlQMTAKMDMgT2N0b2JlciAyMDI0CTIwMjQJUTQJUDEwCjAyIE9jdG9iZXIgMjAyNAkyMDI0CVE0CVAxMAowMSBPY3RvYmVyIDIwMjQJMjAyNAlRNAlQMTAKMzEgTWFyY2ggMjAyMwkyMDIzCVExCVAzCjMwIE1hcmNoIDIwMjMJMjAyMwlRMQlQMwoyOSBNYXJjaCAyMDIzCTIwMjMJUTEJUDMKMjggTWFyY2ggMjAyMwkyMDIzCVExCVAzCjI3IE1hcmNoIDIwMjMJMjAyMwlRMQlQMwoyNiBNYXJjaCAyMDIzCTIwMjMJUTEJUDMKMjUgTWFyY2ggMjAyMwkyMDIzCVExCVAzCjI0IE1hcmNoIDIwMjMJMjAyMwlRMQlQMwoyMyBNYXJjaCAyMDIzCTIwMjMJUTEJUDMKMjIgTWFyY2ggMjAyMwkyMDIzCVExCVAzCjIxIE1hcmNoIDIwMjMJMjAyMwlRMQlQMwoyMCBNYXJjaCAyMDIzCTIwMjMJUTEJUDMKMTkgTWFyY2ggMjAyMwkyMDIzCVExCVAzCjE4IE1hcmNoIDIwMjMJMjAyMwlRMQlQMwoxNyBNYXJjaCAyMDIzCTIwMjMJUTEJUDMKMTYgTWFyY2ggMjAyMwkyMDIzCVExCVAzCjE1IE1hcmNoIDIwMjMJMjAyMwlRMQlQMwoxNCBNYXJjaCAyMDIzCTIwMjMJUTEJUDMKMTMgTWFyY2ggMjAyMwkyMDIzCVExCVAzCjEyIE1hcmNoIDIwMjMJMjAyMwlRMQlQMwoxMSBNYXJjaCAyMDIzCTIwMjMJUTEJUDMKMTAgTWFyY2ggMjAyMwkyMDIzCVExCVAzCjA5IE1hcmNoIDIwMjMJMjAyMwlRMQlQMwowOCBNYXJjaCAyMDIzCTIwMjMJUTEJUDMKMDcgTWFyY2ggMjAyMwkyMDIzCVExCVAzCjA2IE1hcmNoIDIwMjMJMjAyMwlRMQlQMwowNSBNYXJjaCAyMDIzCTIwMjMJUTEJUDMKMDQgTWFyY2ggMjAyMwkyMDIzCVExCVAzCjAzIE1hcmNoIDIwMjMJMjAyMwlRMQlQMwowMiBNYXJjaCAyMDIzCTIwMjMJUTEJUDMKMDEgTWFyY2ggMjAyMwkyMDIzCVExCVAzCjI4IEZlYnJ1YXJ5IDIwMjMJMjAyMwlRMQlQMgoyNyBGZWJydWFyeSAyMDIzCTIwMjMJUTEJUDIKMjYgRmVicnVhcnkgMjAyMwkyMDIzCVExCVAyCjI1IEZlYnJ1YXJ5IDIwMjMJMjAyMwlRMQlQMgoyNCBGZWJydWFyeSAyMDIzCTIwMjMJUTEJUDIKMjMgRmVicnVhcnkgMjAyMwkyMDIzCVExCVAyCjIyIEZlYnJ1YXJ5IDIwMjMJMjAyMwlRMQlQMgoyMSBGZWJydWFyeSAyMDIzCTIwMjMJUTEJUDIKMjAgRmVicnVhcnkgMjAyMwkyMDIzCVExCVAyCjE5IEZlYnJ1YXJ5IDIwMjMJMjAyMwlRMQlQMgoxOCBGZWJydWFyeSAyMDIzCTIwMjMJUTEJUDIKMTcgRmVicnVhcnkgMjAyMwkyMDIzCVExCVAyCjE2IEZlYnJ1YXJ5IDIwMjMJMjAyMwlRMQlQMgoxNSBGZWJydWFyeSAyMDIzCTIwMjMJUTEJUDIKMTQgRmVicnVhcnkgMjAyMwkyMDIzCVExCVAyCjEzIEZlYnJ1YXJ5IDIwMjMJMjAyMwlRMQlQMgoxMiBGZWJydWFyeSAyMDIzCTIwMjMJUTEJUDIKMTEgRmVicnVhcnkgMjAyMwkyMDIzCVExCVAyCjEwIEZlYnJ1YXJ5IDIwMjMJMjAyMwlRMQlQMgowOSBGZWJydWFyeSAyMDIzCTIwMjMJUTEJUDIKMDggRmVicnVhcnkgMjAyMwkyMDIzCVExCVAyCjA3IEZlYnJ1YXJ5IDIwMjMJMjAyMwlRMQlQMgowNiBGZWJydWFyeSAyMDIzCTIwMjMJUTEJUDIKMDUgRmVicnVhcnkgMjAyMwkyMDIzCVExCVAyCjA0IEZlYnJ1YXJ5IDIwMjMJMjAyMwlRMQlQMgowMyBGZWJydWFyeSAyMDIzCTIwMjMJUTEJUDIKMDIgRmVicnVhcnkgMjAyMwkyMDIzCVExCVAyCjAxIEZlYnJ1YXJ5IDIwMjMJMjAyMwlRMQlQMgozMSBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQozMCBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoyOSBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoyOCBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoyNyBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoyNiBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoyNSBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoyNCBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoyMyBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoyMiBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoyMSBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoyMCBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoxOSBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoxOCBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoxNyBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoxNiBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoxNSBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoxNCBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoxMyBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoxMiBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoxMSBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQoxMCBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQowOSBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQowOCBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQowNyBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQowNiBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQowNSBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQowNCBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQowMyBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQowMiBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQowMSBKYW51YXJ5IDIwMjMJMjAyMwlRMQlQMQozMSBNYXJjaCAyMDI0CTIwMjQJUTEJUDMKMzAgTWFyY2ggMjAyNAkyMDI0CVExCVAzCjI5IE1hcmNoIDIwMjQJMjAyNAlRMQlQMwoyOCBNYXJjaCAyMDI0CTIwMjQJUTEJUDMKMjcgTWFyY2ggMjAyNAkyMDI0CVExCVAzCjI2IE1hcmNoIDIwMjQJMjAyNAlRMQlQMwoyNSBNYXJjaCAyMDI0CTIwMjQJUTEJUDMKMjQgTWFyY2ggMjAyNAkyMDI0CVExCVAzCjIzIE1hcmNoIDIwMjQJMjAyNAlRMQlQMwoyMiBNYXJjaCAyMDI0CTIwMjQJUTEJUDMKMjEgTWFyY2ggMjAyNAkyMDI0CVExCVAzCjIwIE1hcmNoIDIwMjQJMjAyNAlRMQlQMwoxOSBNYXJjaCAyMDI0CTIwMjQJUTEJUDMKMTggTWFyY2ggMjAyNAkyMDI0CVExCVAzCjE3IE1hcmNoIDIwMjQJMjAyNAlRMQlQMwoxNiBNYXJjaCAyMDI0CTIwMjQJUTEJUDMKMTUgTWFyY2ggMjAyNAkyMDI0CVExCVAzCjE0IE1hcmNoIDIwMjQJMjAyNAlRMQlQMwoxMyBNYXJjaCAyMDI0CTIwMjQJUTEJUDMKMTIgTWFyY2ggMjAyNAkyMDI0CVExCVAzCjExIE1hcmNoIDIwMjQJMjAyNAlRMQlQMwoxMCBNYXJjaCAyMDI0CTIwMjQJUTEJUDMKMDkgTWFyY2ggMjAyNAkyMDI0CVExCVAzCjA4IE1hcmNoIDIwMjQJMjAyNAlRMQlQMwowNyBNYXJjaCAyMDI0CTIwMjQJUTEJUDMKMDYgTWFyY2ggMjAyNAkyMDI0CVExCVAzCjA1IE1hcmNoIDIwMjQJMjAyNAlRMQlQMwowNCBNYXJjaCAyMDI0CTIwMjQJUTEJUDMKMDMgTWFyY2ggMjAyNAkyMDI0CVExCVAzCjAyIE1hcmNoIDIwMjQJMjAyNAlRMQlQMwowMSBNYXJjaCAyMDI0CTIwMjQJUTEJUDMKMjkgRmVicnVhcnkgMjAyNAkyMDI0CVExCVAyCjI4IEZlYnJ1YXJ5IDIwMjQJMjAyNAlRMQlQMgoyNyBGZWJydWFyeSAyMDI0CTIwMjQJUTEJUDIKMjYgRmVicnVhcnkgMjAyNAkyMDI0CVExCVAyCjI1IEZlYnJ1YXJ5IDIwMjQJMjAyNAlRMQlQMgoyNCBGZWJydWFyeSAyMDI0CTIwMjQJUTEJUDIKMjMgRmVicnVhcnkgMjAyNAkyMDI0CVExCVAyCjIyIEZlYnJ1YXJ5IDIwMjQJMjAyNAlRMQlQMgoyMSBGZWJydWFyeSAyMDI0CTIwMjQJUTEJUDIKMjAgRmVicnVhcnkgMjAyNAkyMDI0CVExCVAyCjE5IEZlYnJ1YXJ5IDIwMjQJMjAyNAlRMQlQMgoxOCBGZWJydWFyeSAyMDI0CTIwMjQJUTEJUDIKMTcgRmVicnVhcnkgMjAyNAkyMDI0CVExCVAyCjE2IEZlYnJ1YXJ5IDIwMjQJMjAyNAlRMQlQMgoxNSBGZWJydWFyeSAyMDI0CTIwMjQJUTEJUDIKMTQgRmVicnVhcnkgMjAyNAkyMDI0CVExCVAyCjEzIEZlYnJ1YXJ5IDIwMjQJMjAyNAlRMQlQMgoxMiBGZWJydWFyeSAyMDI0CTIwMjQJUTEJUDIKMTEgRmVicnVhcnkgMjAyNAkyMDI0CVExCVAyCjEwIEZlYnJ1YXJ5IDIwMjQJMjAyNAlRMQlQMgowOSBGZWJydWFyeSAyMDI0CTIwMjQJUTEJUDIKMDggRmVicnVhcnkgMjAyNAkyMDI0CVExCVAyCjA3IEZlYnJ1YXJ5IDIwMjQJMjAyNAlRMQlQMgowNiBGZWJydWFyeSAyMDI0CTIwMjQJUTEJUDIKMDUgRmVicnVhcnkgMjAyNAkyMDI0CVExCVAyCjA0IEZlYnJ1YXJ5IDIwMjQJMjAyNAlRMQlQMgowMyBGZWJydWFyeSAyMDI0CTIwMjQJUTEJUDIKMDIgRmVicnVhcnkgMjAyNAkyMDI0CVExCVAyCjAxIEZlYnJ1YXJ5IDIwMjQJMjAyNAlRMQlQMgozMSBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQozMCBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoyOSBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoyOCBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoyNyBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoyNiBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoyNSBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoyNCBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoyMyBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoyMiBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoyMSBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoyMCBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoxOSBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoxOCBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoxNyBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoxNiBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoxNSBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoxNCBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoxMyBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoxMiBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoxMSBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQoxMCBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQowOSBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQowOCBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQowNyBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQowNiBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQowNSBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQowNCBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQowMyBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQowMiBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQowMSBKYW51YXJ5IDIwMjQJMjAyNAlRMQlQMQozMCBKdW5lIDIwMjMJMjAyMwlRMglQNgoyOSBKdW5lIDIwMjMJMjAyMwlRMglQNgoyOCBKdW5lIDIwMjMJMjAyMwlRMglQNgoyNyBKdW5lIDIwMjMJMjAyMwlRMglQNgoyNiBKdW5lIDIwMjMJMjAyMwlRMglQNgoyNSBKdW5lIDIwMjMJMjAyMwlRMglQNgoyNCBKdW5lIDIwMjMJMjAyMwlRMglQNgoyMyBKdW5lIDIwMjMJMjAyMwlRMglQNgoyMiBKdW5lIDIwMjMJMjAyMwlRMglQNgoyMSBKdW5lIDIwMjMJMjAyMwlRMglQNgoyMCBKdW5lIDIwMjMJMjAyMwlRMglQNgoxOSBKdW5lIDIwMjMJMjAyMwlRMglQNgoxOCBKdW5lIDIwMjMJMjAyMwlRMglQNgoxNyBKdW5lIDIwMjMJMjAyMwlRMglQNgoxNiBKdW5lIDIwMjMJMjAyMwlRMglQNgoxNSBKdW5lIDIwMjMJMjAyMwlRMglQNgoxNCBKdW5lIDIwMjMJMjAyMwlRMglQNgoxMyBKdW5lIDIwMjMJMjAyMwlRMglQNgoxMiBKdW5lIDIwMjMJMjAyMwlRMglQNgoxMSBKdW5lIDIwMjMJMjAyMwlRMglQNgoxMCBKdW5lIDIwMjMJMjAyMwlRMglQNgowOSBKdW5lIDIwMjMJMjAyMwlRMglQNgowOCBKdW5lIDIwMjMJMjAyMwlRMglQNgowNyBKdW5lIDIwMjMJMjAyMwlRMglQNgowNiBKdW5lIDIwMjMJMjAyMwlRMglQNgowNSBKdW5lIDIwMjMJMjAyMwlRMglQNgowNCBKdW5lIDIwMjMJMjAyMwlRMglQNgowMyBKdW5lIDIwMjMJMjAyMwlRMglQNgowMiBKdW5lIDIwMjMJMjAyMwlRMglQNgowMSBKdW5lIDIwMjMJMjAyMwlRMglQNgozMSBNYXkgMjAyMwkyMDIzCVEyCVA1CjMwIE1heSAyMDIzCTIwMjMJUTIJUDUKMjkgTWF5IDIwMjMJMjAyMwlRMglQNQoyOCBNYXkgMjAyMwkyMDIzCVEyCVA1CjI3IE1heSAyMDIzCTIwMjMJUTIJUDUKMjYgTWF5IDIwMjMJMjAyMwlRMglQNQoyNSBNYXkgMjAyMwkyMDIzCVEyCVA1CjI0IE1heSAyMDIzCTIwMjMJUTIJUDUKMjMgTWF5IDIwMjMJMjAyMwlRMglQNQoyMiBNYXkgMjAyMwkyMDIzCVEyCVA1CjIxIE1heSAyMDIzCTIwMjMJUTIJUDUKMjAgTWF5IDIwMjMJMjAyMwlRMglQNQoxOSBNYXkgMjAyMwkyMDIzCVEyCVA1CjE4IE1heSAyMDIzCTIwMjMJUTIJUDUKMTcgTWF5IDIwMjMJMjAyMwlRMglQNQoxNiBNYXkgMjAyMwkyMDIzCVEyCVA1CjE1IE1heSAyMDIzCTIwMjMJUTIJUDUKMTQgTWF5IDIwMjMJMjAyMwlRMglQNQoxMyBNYXkgMjAyMwkyMDIzCVEyCVA1CjEyIE1heSAyMDIzCTIwMjMJUTIJUDUKMTEgTWF5IDIwMjMJMjAyMwlRMglQNQoxMCBNYXkgMjAyMwkyMDIzCVEyCVA1CjA5IE1heSAyMDIzCTIwMjMJUTIJUDUKMDggTWF5IDIwMjMJMjAyMwlRMglQNQowNyBNYXkgMjAyMwkyMDIzCVEyCVA1CjA2IE1heSAyMDIzCTIwMjMJUTIJUDUKMDUgTWF5IDIwMjMJMjAyMwlRMglQNQowNCBNYXkgMjAyMwkyMDIzCVEyCVA1CjAzIE1heSAyMDIzCTIwMjMJUTIJUDUKMDIgTWF5IDIwMjMJMjAyMwlRMglQNQowMSBNYXkgMjAyMwkyMDIzCVEyCVA1CjMwIEFwcmlsIDIwMjMJMjAyMwlRMglQNAoyOSBBcHJpbCAyMDIzCTIwMjMJUTIJUDQKMjggQXByaWwgMjAyMwkyMDIzCVEyCVA0CjI3IEFwcmlsIDIwMjMJMjAyMwlRMglQNAoyNiBBcHJpbCAyMDIzCTIwMjMJUTIJUDQKMjUgQXByaWwgMjAyMwkyMDIzCVEyCVA0CjI0IEFwcmlsIDIwMjMJMjAyMwlRMglQNAoyMyBBcHJpbCAyMDIzCTIwMjMJUTIJUDQKMjIgQXByaWwgMjAyMwkyMDIzCVEyCVA0CjIxIEFwcmlsIDIwMjMJMjAyMwlRMglQNAoyMCBBcHJpbCAyMDIzCTIwMjMJUTIJUDQKMTkgQXByaWwgMjAyMwkyMDIzCVEyCVA0CjE4IEFwcmlsIDIwMjMJMjAyMwlRMglQNAoxNyBBcHJpbCAyMDIzCTIwMjMJUTIJUDQKMTYgQXByaWwgMjAyMwkyMDIzCVEyCVA0CjE1IEFwcmlsIDIwMjMJMjAyMwlRMglQNAoxNCBBcHJpbCAyMDIzCTIwMjMJUTIJUDQKMTMgQXByaWwgMjAyMwkyMDIzCVEyCVA0CjEyIEFwcmlsIDIwMjMJMjAyMwlRMglQNAoxMSBBcHJpbCAyMDIzCTIwMjMJUTIJUDQKMTAgQXByaWwgMjAyMwkyMDIzCVEyCVA0CjA5IEFwcmlsIDIwMjMJMjAyMwlRMglQNAowOCBBcHJpbCAyMDIzCTIwMjMJUTIJUDQKMDcgQXByaWwgMjAyMwkyMDIzCVEyCVA0CjA2IEFwcmlsIDIwMjMJMjAyMwlRMglQNAowNSBBcHJpbCAyMDIzCTIwMjMJUTIJUDQKMDQgQXByaWwgMjAyMwkyMDIzCVEyCVA0CjAzIEFwcmlsIDIwMjMJMjAyMwlRMglQNAowMiBBcHJpbCAyMDIzCTIwMjMJUTIJUDQKMDEgQXByaWwgMjAyMwkyMDIzCVEyCVA0CjMwIEp1bmUgMjAyNAkyMDI0CVEyCVA2CjI5IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjI4IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjI3IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjI2IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjI1IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjI0IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjIzIEp1bmUgMjAyNAkyMDI0CVEyCVA2CjIyIEp1bmUgMjAyNAkyMDI0CVEyCVA2CjIxIEp1bmUgMjAyNAkyMDI0CVEyCVA2CjIwIEp1bmUgMjAyNAkyMDI0CVEyCVA2CjE5IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjE4IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjE3IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjE2IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjE1IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjE0IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjEzIEp1bmUgMjAyNAkyMDI0CVEyCVA2CjEyIEp1bmUgMjAyNAkyMDI0CVEyCVA2CjExIEp1bmUgMjAyNAkyMDI0CVEyCVA2CjEwIEp1bmUgMjAyNAkyMDI0CVEyCVA2CjA5IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjA4IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjA3IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjA2IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjA1IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjA0IEp1bmUgMjAyNAkyMDI0CVEyCVA2CjAzIEp1bmUgMjAyNAkyMDI0CVEyCVA2CjAyIEp1bmUgMjAyNAkyMDI0CVEyCVA2CjAxIEp1bmUgMjAyNAkyMDI0CVEyCVA2CjMxIE1heSAyMDI0CTIwMjQJUTIJUDUKMzAgTWF5IDIwMjQJMjAyNAlRMglQNQoyOSBNYXkgMjAyNAkyMDI0CVEyCVA1CjI4IE1heSAyMDI0CTIwMjQJUTIJUDUKMjcgTWF5IDIwMjQJMjAyNAlRMglQNQoyNiBNYXkgMjAyNAkyMDI0CVEyCVA1CjI1IE1heSAyMDI0CTIwMjQJUTIJUDUKMjQgTWF5IDIwMjQJMjAyNAlRMglQNQoyMyBNYXkgMjAyNAkyMDI0CVEyCVA1CjIyIE1heSAyMDI0CTIwMjQJUTIJUDUKMjEgTWF5IDIwMjQJMjAyNAlRMglQNQoyMCBNYXkgMjAyNAkyMDI0CVEyCVA1CjE5IE1heSAyMDI0CTIwMjQJUTIJUDUKMTggTWF5IDIwMjQJMjAyNAlRMglQNQoxNyBNYXkgMjAyNAkyMDI0CVEyCVA1CjE2IE1heSAyMDI0CTIwMjQJUTIJUDUKMTUgTWF5IDIwMjQJMjAyNAlRMglQNQoxNCBNYXkgMjAyNAkyMDI0CVEyCVA1CjEzIE1heSAyMDI0CTIwMjQJUTIJUDUKMTIgTWF5IDIwMjQJMjAyNAlRMglQNQoxMSBNYXkgMjAyNAkyMDI0CVEyCVA1CjEwIE1heSAyMDI0CTIwMjQJUTIJUDUKMDkgTWF5IDIwMjQJMjAyNAlRMglQNQowOCBNYXkgMjAyNAkyMDI0CVEyCVA1CjA3IE1heSAyMDI0CTIwMjQJUTIJUDUKMDYgTWF5IDIwMjQJMjAyNAlRMglQNQowNSBNYXkgMjAyNAkyMDI0CVEyCVA1CjA0IE1heSAyMDI0CTIwMjQJUTIJUDUKMDMgTWF5IDIwMjQJMjAyNAlRMglQNQowMiBNYXkgMjAyNAkyMDI0CVEyCVA1CjAxIE1heSAyMDI0CTIwMjQJUTIJUDUKMzAgQXByaWwgMjAyNAkyMDI0CVEyCVA0CjI5IEFwcmlsIDIwMjQJMjAyNAlRMglQNAoyOCBBcHJpbCAyMDI0CTIwMjQJUTIJUDQKMjcgQXByaWwgMjAyNAkyMDI0CVEyCVA0CjI2IEFwcmlsIDIwMjQJMjAyNAlRMglQNAoyNSBBcHJpbCAyMDI0CTIwMjQJUTIJUDQKMjQgQXByaWwgMjAyNAkyMDI0CVEyCVA0CjIzIEFwcmlsIDIwMjQJMjAyNAlRMglQNAoyMiBBcHJpbCAyMDI0CTIwMjQJUTIJUDQKMjEgQXByaWwgMjAyNAkyMDI0CVEyCVA0CjIwIEFwcmlsIDIwMjQJMjAyNAlRMglQNAoxOSBBcHJpbCAyMDI0CTIwMjQJUTIJUDQKMTggQXByaWwgMjAyNAkyMDI0CVEyCVA0CjE3IEFwcmlsIDIwMjQJMjAyNAlRMglQNAoxNiBBcHJpbCAyMDI0CTIwMjQJUTIJUDQKMTUgQXByaWwgMjAyNAkyMDI0CVEyCVA0CjE0IEFwcmlsIDIwMjQJMjAyNAlRMglQNAoxMyBBcHJpbCAyMDI0CTIwMjQJUTIJUDQKMTIgQXByaWwgMjAyNAkyMDI0CVEyCVA0CjExIEFwcmlsIDIwMjQJMjAyNAlRMglQNAoxMCBBcHJpbCAyMDI0CTIwMjQJUTIJUDQKMDkgQXByaWwgMjAyNAkyMDI0CVEyCVA0CjA4IEFwcmlsIDIwMjQJMjAyNAlRMglQNAowNyBBcHJpbCAyMDI0CTIwMjQJUTIJUDQKMDYgQXByaWwgMjAyNAkyMDI0CVEyCVA0CjA1IEFwcmlsIDIwMjQJMjAyNAlRMglQNAowNCBBcHJpbCAyMDI0CTIwMjQJUTIJUDQKMDMgQXByaWwgMjAyNAkyMDI0CVEyCVA0CjAyIEFwcmlsIDIwMjQJMjAyNAlRMglQNAowMSBBcHJpbCAyMDI0CTIwMjQJUTIJUDQ="    , BinaryEncoding.Base64),
				    #"Imported CSV" = Csv.Document(Source,[Delimiter="#(tab)", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Fiscal Date", type date}, {"Fiscal Year", Int64.Type}, {"Fiscal Quarter", type text}, {"Fiscal Period", type text}})
				
				
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = Dimensions

