createOrReplace

	table _Measures
		lineageTag: 5bced19d-0fbc-4db8-b710-4bd7ec18852d

		measure Actuals =
				
				__Fn_PnL_Sum_Subtotal_and_Blanks (sum(Ledger[Credit Less Debit @Global Fx]))
			formatString: #,##0,;(#,##0,);
			lineageTag: dfdd07d8-551c-435f-bd10-c40ef0ee0c23

			annotation PBI_FormatHint = {"isCustom":true}

		measure Plan =
				
				__Fn_PnL_Sum_Subtotal_and_Blanks (calculate(sum(Scenario[Credit less debit]),Scenario[Scenario Key]=1))
			formatString: " #,##0,;(#,##0,);"
			lineageTag: 706d8174-5120-4e62-84a5-6c08cbefb30b

			annotation PBI_FormatHint = {"isCustom":true}

		partition _Measures = m
			mode: import
			source =
					let
					    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
					    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
					    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
					in
					    #"Removed Columns"

		annotation PBI_NavigationStepName = Navigation

		annotation PBI_ResultType = Table


		measure 'Top down forecast' =
				
				__Fn_PnL_Sum_Subtotal_and_Blanks (calculate(sum(Scenario[Credit less debit]),Scenario[Scenario Key]=2))
			formatString: " #,##0,;(#,##0,);"


			annotation PBI_FormatHint = {"isCustom":true}


		measure 'Bottop up forecast' =
				
				__Fn_PnL_Sum_Subtotal_and_Blanks (calculate(sum(Scenario[Credit less debit]),Scenario[Scenario Key]=2))
			formatString: " #,##0,;(#,##0,);"


			annotation PBI_FormatHint = {"isCustom":true}