createOrReplace

	ref table _Measures

		measure 'Var, #' =
				
			
			formatString: #,##0,;(#,##0,);
			lineageTag: dfdd07d8-551c-435f-bd10-c40ef0ee0c23

			annotation PBI_FormatHint = {"isCustom":true}

